### ISSUE TITLE
How does this differ from rentzsch/OAuthConsumer?

### ISSUE THREAD

**Issue by sethfitz** [jdg/oauthconsumer#2]
How does this differ from https://github.com/rentzsch/OAuthConsumer ?

**Comment by sethfitz** [comment]
See  also https://github.com/rentzsch/OAuthConsumer/issues/issue/2

**Comment by jdg** [comment]
No clue, his is probably better.

**Comment by rentzsch** [comment]
heh, I was going to say yours is probably better :-)

Looks like yours is more iPhone-y and mine is more Mac-y.

**Comment by jdg** [comment]
I'd have to agree with you on that one rentzsch!  :)

(I've only used my repo in an iPhone app, not on the desktop yet.)

**Comment by sethfitz** [comment]
Glad to introduce you guys.  ;-)

Thanks for the enlightenment.
