### ISSUE TITLE
Can't build since change to u_int32_t and u_int8_t

### ISSUE THREAD

**Issue by dhardiman** [jdg/oauthconsumer#3]
I've just pulled the latest commit, and since the change from unsigned long and unsigned char to u_int32_t and u_int8_t, I get build errors of undefined types.  Am I missing a project setting?

**Comment by kazkam** [comment]
#include <sys/types.h>

**Comment by dhardiman** [comment]
Great, thanks

**Comment by scootklein** [comment]
should consider putting this in the README

**Comment by jdg** [comment]
Noted in the readme.
