### ISSUE TITLE
recent commit 4e26cb9c4338024a81f0c192c12a7708ad5c11c4 breaks on iphone sdk

### ISSUE THREAD

**Issue by scootklein** [jdg/oauthconsumer#4]
The most recent commit to change to explicit type sizes won't build with the most recent iOS SDK due to it not being able to recognize u_int8_t (among others)

Are there any flags that we need for it to recognize these symbols?

https://github.com/jdg/oauthconsumer/commit/4e26cb9c4338024a81f0c192c12a7708ad5c11c4

**Comment by scootklein** [comment]
my fault, new to github and didn't see the "unread" tab for issues. this is a duplicate.

**Comment by jdg** [comment]
No problem.  I just reverted the commit; let me know if it still exists.
